routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('admin/home');
})->name('start');

Route::get('/admin', function () {
    return redirect('admin/home');
});
Route::get('/home', function () {
    return redirect('admin/home');
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');


Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('permissions', 'Admin\PermissionsController',['only' => [
    'index', 'create', 'store', 'edit', 'update'
    ]])
    ->middleware('can:permissions_manage');

    Route::resource('roles', 'Admin\RolesController',['only' => [
    'index', 'create', 'store', 'edit', 'update'
    ]])
    ->middleware('can:roles_manage');

    Route::resource('users', 'Admin\UsersController',['only' => [
    'index', 'create', 'store', 'edit', 'update'
    ]])
    ->middleware('can:users_manage');

    Route::resource('menus', 'Admin\MenusController',['only' => [
    'index', 'create', 'store', 'edit', 'update'
    ]])
    ->middleware('can:menus_manage');

    Route::get('panel/account', 'Admin\PanelController@account')->name('panel.account');
    Route::post('panel/account', 'Admin\PanelController@update')->name('panel.update');

    Route::get('panel/account', 'Admin\PanelController@account')->name('panel.account');
    Route::post('panel/account', 'Admin\PanelController@update')->name('panel.update');
    Route::get('panel/change_password', 'Admin\PanelController@change_password')->name('panel.change_password');
    Route::post('panel/change_password', 'Admin\PanelController@change_passwd')->name('panel.change_passwd');

});

app/Http/Controllers/Admin/PanelController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use Auth;
use Image;
use Hash;

class PanelController extends Controller
{
  public function account()
  {
    return view('admin.panel.account', array('user' => Auth::user()));
  }

  public function update(Request $request)
  {
    request()->validate([
            'avatar' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);
    $imageName = time().'.'.request()->avatar->getClientOriginalExtension();
    request()->avatar->move(public_path('uploads/avatar'), $imageName);

    $user = Auth::user();
    $user->avatar = $imageName;
    $user->save();
    return back()
          ->with('success','You have successfully upload profile picture.')
          ->with('avatar',$imageName);
  }

  public function change_password()
  {
    return view('admin.panel.change_password');
  }

  public function change_passwd(Request $request)
  {
    request()->validate([
          'old_password' => 'required',
          'new_password' => 'required|string|min:6|confirmed',
      ]);
    $user = Auth::user();
    if(!Hash::check($request->old_password, $user->password)){
      return back()->with("error","Your current password does not matches with the password you provided. Please try again.");
    }

    if(strcmp($request->get('old_password'), $request->get('new_password')) == 0){
      //Current password and new password are same
      return back()->with("error","New Password cannot be same as your current password. Please choose a different password.");
    }

    $user->password = bcrypt($request->get('new_password'));
    $user->save();
    return back()
          ->with('success',"Password changed successfully !");
  }
}

resources/views/admin/panel/account.blade.php
@extends('adminlte::page')

@section('content')
  @if ($message = Session::get('success'))
    <div class="alert alert-success alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>{{ $message }}</strong>
    </div>
  @endif
  @if (count($errors) > 0)
      <div class="alert alert-danger">
          <strong>Whoops!</strong> There were some problems with your input.
          <ul>
              @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
              @endforeach
          </ul>
      </div>
  @endif
  <div class="container">
    <div class="row">
      <div class="col-md-5 col-md-offset-1">
        <h1>Account Details</h1>
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('name', 'Name', ['class' => 'control-label']) !!}
                    {!! Form::text('name', Auth::user()->name, ['class' => 'form-control', 'placeholder' => '', 'required' => '', 'readonly' => 'readonly']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('name'))
                        <p class="help-block">
                            {{ $errors->first('name') }}
                        </p>
                    @endif
                </div>
                <div class="col-xs-12 form-group">
                    {!! Form::label('email', 'Email', ['class' => 'control-label']) !!}
                    {!! Form::text('email', Auth::user()->email, ['class' => 'form-control', 'placeholder' => '', 'required' => '', 'readonly' => 'readonly']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('email'))
                        <p class="help-block">
                            {{ $errors->first('email') }}
                        </p>
                    @endif
                </div>
                <div class="col-xs-12 form-group">
                    {!! Form::label('api_token', 'API Token', ['class' => 'control-label']) !!}
                    {!! Form::button('Show',['onclick' => "$('#api_token').toggle()"]) !!}
                    {!! Form::text('api_token', Auth::user()->api_token, ['class' => 'form-control', 'placeholder' => '', 'required' => '', 'readonly' => 'readonly', 'style' => 'display:none;']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('api_token'))
                        <p class="help-block">
                            {{ $errors->first('api_token') }}
                        </p>
                    @endif
                </div>
                <form enctype="multipart/form-data" action="{{ route('admin.panel.update') }}" method="POST">
                  <div class="col-xs-12 form-group">
                    <img src="/uploads/avatar/{{ $user->avatar }}" style="width:150px; height:150px; float:left; border-radius:50%; margin-right:25px;">
                    <h2>{{ $user->name }}'s Profile</h2>
                    <label>Update Profile Image</label>
                    <input type="file" name="avatar">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                  </div>
                  <div class="col-xs-12 form-group">
                    <a href="{{ route('admin.panel.change_password') }}" class="pull-left btn btn-sm btn-warning">Change Password</a>
                    <input type="submit" value="Save" class="pull-right btn btn-sm btn-primary">
                  </div>
                </form>
            </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/admin/panel/change_password.blade.php
@extends('adminlte::page')

@section('content')
  @if ($message = Session::get('error'))
    <div class="alert alert-danger alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>{{ $message }}</strong>
    </div>
  @endif
  @if ($message = Session::get('success'))
    <div class="alert alert-success alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>{{ $message }}</strong>
    </div>
  @endif
  @if (count($errors) > 0)
      <div class="alert alert-danger">
          <strong>Whoops!</strong> There were some problems with your input.
          <ul>
              @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
              @endforeach
          </ul>
      </div>
  @endif
  <div class="container">
    <div class="row">
      <div class="col-md-5 col-md-offset-1">
        <h1>Change Password</h1>
        <div class="panel-body">
          <div class="row">
            <div class="col-xs-12 form-group">
              {!! Form::open(['route' => 'admin.panel.change_passwd', 'method' => 'post']) !!}
              {!! Form::label('old_password', 'Old Password', ['class' => 'control-label']) !!}
              {!! Form::password('old_password', ['class' => 'form-control']); !!}
              {!! Form::label('new_password', 'New Password', ['class' => 'control-label']) !!}
              {!! Form::password('new_password', ['class' => 'form-control']); !!}
              {!! Form::label('new_password_confirmation', 'Confirm New Password', ['class' => 'control-label']) !!}
              {!! Form::password('new_password_confirmation', ['class' => 'form-control']); !!}
              <p class="help-block"></p>
              <input type="submit" value="Save Password" class="pull-right btn btn-sm btn-primary">
              @if($errors->has('old_password'))
                  <p class="help-block">
                      {{ $errors->first('old_password') }}
                  </p>
              @endif
              {!! Form::close() !!}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

@endsection